name: Lint

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'fix/*'

  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46.x
      - run: deno fmt --check
      - run: deno lint
