name: PR Lint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint PR Title (Feature/Fix Rules)
        uses: amannn/action-semantic-pull-request@v5
        with:
          scopes: server, util
          requireScope: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enforce Branch Naming Convention
        run: |
          if [[ ! $GITHUB_HEAD_REF =~ ^(feat|fix)\/[a-z0-9\-]+$ ]]; then
            echo "Branch name must follow 'feat/<short-description>' or 'fix/<short-description>'"
            exit 1
          fi
